### ISSUE TITLE
CT not on this device

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tappi#14]
```
tappi : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654772447480%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught Error: not on this device!
Error: not on this device!
at new gI (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654772447480%7D&fuzz&memoryLimit=1000:890:1425457)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654772447480%7D&fuzz&memoryLimit=1000:890:1428835)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654772447480%7D&fuzz&memoryLimit=1000:890:1433444)
at Object.phet.chipper.runWebpack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654772447480%7D&fuzz&memoryLimit=1000:890:1433448)
at i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654772447480%7D&fuzz&memoryLimit=1000:891:1040)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654772447480%7D&fuzz&memoryLimit=1000:891:1068)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654772447480%7D&fuzz&memoryLimit=1000:891:1093)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654772447480%7D&fuzz&memoryLimit=1000:891:1195)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM

----------------------------------

tappi : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654776864475%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught Error: not on this device!
Error: not on this device!
at new gI (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654776864475%7D&fuzz&memoryLimit=1000:890:1425457)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654776864475%7D&fuzz&memoryLimit=1000:890:1428835)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654776864475%7D&fuzz&memoryLimit=1000:890:1433444)
at Object.phet.chipper.runWebpack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654776864475%7D&fuzz&memoryLimit=1000:890:1433448)
at i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654776864475%7D&fuzz&memoryLimit=1000:891:1040)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654776864475%7D&fuzz&memoryLimit=1000:891:1068)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654776864475%7D&fuzz&memoryLimit=1000:891:1093)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/build/phet/tappi_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654776864475%7D&fuzz&memoryLimit=1000:891:1195)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM

----------------------------------

tappi : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/tappi_en.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654771608277%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: not on this device!
Error: not on this device!
at (VibrationManageriOS.ts:23:12)
at (VibrationPatterns.ts:15:25)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM

----------------------------------

tappi : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/tappi_en.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654777123098%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: not on this device!
Error: not on this device!
at (VibrationManageriOS.ts:23:12)
at (VibrationPatterns.ts:15:25)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM

----------------------------------

tappi : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/tappi_en.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654775912862%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: not on this device!
Error: not on this device!
at (VibrationManageriOS.ts:23:12)
at (VibrationPatterns.ts:15:25)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM

----------------------------------

tappi : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/tappi_en.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654770428953%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: not on this device!
Error: not on this device!
at (VibrationManageriOS.ts:23:12)
at (VibrationPatterns.ts:15:25)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM

----------------------------------

tappi : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/tappi_en.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654777766610%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: not on this device!
Error: not on this device!
at (VibrationManageriOS.ts:23:12)
at (VibrationPatterns.ts:15:25)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM

----------------------------------

tappi : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/tappi_en.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654770498377%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: not on this device!
Error: not on this device!
at (VibrationManageriOS.ts:23:12)
at (VibrationPatterns.ts:15:25)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM

----------------------------------

tappi : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/tappi_en.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654778365956%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: not on this device!
Error: not on this device!
at (VibrationManageriOS.ts:23:12)
at (VibrationPatterns.ts:15:25)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM

----------------------------------

tappi : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/tappi_en.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654772171068%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: not on this device!
Error: not on this device!
at (VibrationManageriOS.ts:23:12)
at (VibrationPatterns.ts:15:25)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM

----------------------------------

tappi : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654768985977/tappi/tappi_en.html?continuousTest=%7B%22test%22%3A%5B%22tappi%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1654768985977%22%2C%22timestamp%22%3A1654779788498%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: not on this device!
Error: not on this device!
at (VibrationManageriOS.ts:23:12)
at (VibrationPatterns.ts:15:25)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 4:03:05 AM
```

**Comment by jbphet** [comment]
This is the result of some things that I did while converting to TypeScript.  I'll make an immediate fix, but I think I might need @jessegreenberg for the long-term solution.

**Comment by jbphet** [comment]
@jessegreenberg - I made a commit that I think will fix the immediate CT issue, but I don't understand enough about what the `VibrationManageriOS` class is all about to do much more than this.  Please have a look and see if you can come up with a better, more permanent fix.

**Comment by jbphet** [comment]
I just checked CT, and it has indeed cleared up after the previous commit.

![image](https://user-images.githubusercontent.com/3082831/172955987-38eeb341-c77e-4050-806e-08d356795fd4.png)

**Comment by jessegreenberg** [comment]
Thanks for working on this. This came up again in #15 because `webkit` is only available on mobile safari. To fix this I changed `VibrationPatterns.interactionSuccess` to take an instance of a VibrationManageriOS instead of using an instance that gets constructed during module imports. I think that will generally prevent hitting this error outside of the prototype code that uses VibrationManageriOS.

There is one more place where this should be done in ContinuousPatternVibrationController, I will do the same thing there.

**Comment by jessegreenberg** [comment]
Done in the above commit, the only usages of VibrationManageriOS are now hidden behind the `?vibrationParadigm` query parameter. I think that is sufficient for this issue. I added an `@deprecated` note to VibrationManageriOS. @jbphet feel free to review and please reopen if you think there is more to be done here, but going to go ahead and close.
